import type { CreditCard } from "./BottomCardSection.types";

export const creditCards: CreditCard[] = [
  // HDFC Bank Cards
  {
    id: "hdfc1",
    name: "HDFC Regalia",
    bank: "HDFC Bank",
    image: "/cards/hdfc-regalia.png",
    categories: ["travel", "shopping"],
    cashback: 4,
    annualFee: 2500,
    joiningBonus: 5000,
  },
  {
    id: "hdfc2",
    name: "HDFC Millennia",
    bank: "HDFC Bank",
    image: "/cards/hdfc-millennia.png",
    categories: ["shopping", "food"],
    cashback: 5,
    annualFee: 1000,
    joiningBonus: 1000,
  },
  {
    id: "hdfc3",
    name: "HDFC Diners Club",
    bank: "HDFC Bank",
    image: "/cards/hdfc-diners.png",
    categories: ["travel", "fuel"],
    cashback: 3.3,
    annualFee: 10000,
    joiningBonus: 10000,
  },
  {
    id: "hdfc4",
    name: "HDFC MoneyBack",
    bank: "HDFC Bank",
    image: "/cards/hdfc-moneyback.png",
    categories: ["fuel", "shopping"],
    cashback: 2,
    annualFee: 500,
    joiningBonus: 500,
  },
  {
    id: "hdfc5",
    name: "HDFC Infinia",
    bank: "HDFC Bank",
    image: "/cards/hdfc-infinia.png",
    categories: ["travel", "shopping", "food"],
    cashback: 3.3,
    annualFee: 12500,
    joiningBonus: 12500,
  },

  // SBI Cards
  {
    id: "sbi1",
    name: "SBI Cashback",
    bank: "SBI Card",
    image: "/cards/sbi-cashback.png",
    categories: ["shopping", "fuel"],
    cashback: 5,
    annualFee: 999,
    joiningBonus: 2000,
  },
  {
    id: "sbi2",
    name: "SBI SimplyCLICK",
    bank: "SBI Card",
    image: "/cards/sbi-click.png",
    categories: ["shopping", "food"],
    cashback: 10,
    annualFee: 499,
    joiningBonus: 500,
  },
  {
    id: "sbi3",
    name: "SBI Vistara",
    bank: "SBI Card",
    image: "/cards/sbi-vistara.png",
    categories: ["travel"],
    cashback: 4,
    annualFee: 3000,
    joiningBonus: 3000,
  },
  {
    id: "sbi4",
    name: "SBI Elite",
    bank: "SBI Card",
    image: "/cards/sbi-elite.png",
    categories: ["travel", "shopping"],
    cashback: 3,
    annualFee: 4999,
    joiningBonus: 5000,
  },
  {
    id: "sbi5",
    name: "SBI BPCL",
    bank: "SBI Card",
    image: "/cards/sbi-bpcl.png",
    categories: ["fuel"],
    cashback: 7,
    annualFee: 0,
    joiningBonus: 0,
  },

  // ICICI Bank Cards
  {
    id: "icici1",
    name: "ICICI Amazon Pay",
    bank: "ICICI Bank",
    image: "/cards/icici-amazon.png",
    categories: ["shopping"],
    cashback: 5,
    annualFee: 500,
    joiningBonus: 1000,
  },
  {
    id: "icici2",
    name: "ICICI Sapphiro",
    bank: "ICICI Bank",
    image: "/cards/icici-sapphiro.png",
    categories: ["travel", "shopping", "food"],
    cashback: 3.3,
    annualFee: 3500,
    joiningBonus: 3500,
  },
  {
    id: "icici3",
    name: "ICICI HPCL",
    bank: "ICICI Bank",
    image: "/cards/icici-hpcl.png",
    categories: ["fuel"],
    cashback: 5,
    annualFee: 500,
    joiningBonus: 500,
  },
  {
    id: "icici4",
    name: "ICICI Coral",
    bank: "ICICI Bank",
    image: "/cards/icici-coral.png",
    categories: ["shopping", "food"],
    cashback: 2,
    annualFee: 500,
    joiningBonus: 2000,
  },
  {
    id: "icici5",
    name: "ICICI Emeralde",
    bank: "ICICI Bank",
    image: "/cards/icici-emeralde.png",
    categories: ["travel", "shopping"],
    cashback: 4,
    annualFee: 12000,
    joiningBonus: 12000,
  },

  // Axis Bank Cards
  {
    id: "axis1",
    name: "Axis Flipkart",
    bank: "Axis Bank",
    image: "/cards/axis-flipkart.png",
    categories: ["shopping"],
    cashback: 4,
    annualFee: 500,
    joiningBonus: 500,
  },
  {
    id: "axis2",
    name: "Axis Magnus",
    bank: "Axis Bank",
    image: "/cards/axis-magnus.png",
    categories: ["travel", "shopping", "food"],
    cashback: 4.8,
    annualFee: 12500,
    joiningBonus: 25000,
  },
  {
    id: "axis3",
    name: "Axis Vistara",
    bank: "Axis Bank",
    image: "/cards/axis-vistara.png",
    categories: ["travel"],
    cashback: 4,
    annualFee: 1500,
    joiningBonus: 1500,
  },
  {
    id: "axis4",
    name: "Axis ACE",
    bank: "Axis Bank",
    image: "/cards/axis-ace.png",
    categories: ["shopping", "food", "fuel"],
    cashback: 2,
    annualFee: 0,
    joiningBonus: 0,
  },
  {
    id: "axis5",
    name: "Axis Select",
    bank: "Axis Bank",
    image: "/cards/axis-select.png",
    categories: ["shopping", "travel"],
    cashback: 2,
    annualFee: 3000,
    joiningBonus: 3000,
  },
];
