import type { CreditCard } from "./BottomCardSection.types";

export const creditCards: CreditCard[] = [
  // HDFC Bank Cards
  {
    id: "hdfc1",
    name: "HDFC Regalia",
    bank: "HDFC Bank",
    image: "/cards/hdfc-regalia.png",
    categories: ["travel", "shopping"],
    cashback: 4,
    annualFee: 150,
    joiningBonus: 5000,
    rating: 4.5,
    reviews: 3245,
  },
  {
    id: "hdfc2",
    name: "HDFC Millennia",
    bank: "HDFC Bank",
    image: "/cards/hdfc-millennia.png",
    categories: ["shopping", "food"],
    cashback: 5,
    annualFee: 120,
    joiningBonus: 1000,
    rating: 4.2,
    reviews: 2156,
  },
  {
    id: "hdfc3",
    name: "HDFC Diners Club",
    bank: "HDFC Bank",
    image: "/cards/hdfc-diners.png",
    categories: ["travel", "fuel"],
    cashback: 3.3,
    annualFee: 180,
    joiningBonus: 10000,
    rating: 4.7,
    reviews: 4523,
  },
  {
    id: "hdfc4",
    name: "HDFC MoneyBack",
    bank: "HDFC Bank",
    image: "/cards/hdfc-moneyback.png",
    categories: ["fuel", "shopping"],
    cashback: 2,
    annualFee: 100,
    joiningBonus: 500,
    rating: 3.8,
    reviews: 1876,
  },
  {
    id: "hdfc5",
    name: "HDFC Infinia",
    bank: "HDFC Bank",
    image: "/cards/hdfc-infinia.png",
    categories: ["travel", "shopping", "food"],
    cashback: 3.3,
    annualFee: 200,
    joiningBonus: 12500,
    rating: 4.9,
    reviews: 5621,
  },

  // SBI Cards
  {
    id: "sbi1",
    name: "SBI Cashback",
    bank: "SBI Card",
    image: "/cards/sbi-cashback.png",
    categories: ["shopping", "fuel"],
    cashback: 5,
    annualFee: 140,
    joiningBonus: 2000,
    rating: 4.6,
    reviews: 3890,
  },
  {
    id: "sbi2",
    name: "SBI SimplyCLICK",
    bank: "SBI Card",
    image: "/cards/sbi-click.png",
    categories: ["shopping", "food"],
    cashback: 10,
    annualFee: 110,
    joiningBonus: 500,
    rating: 4.3,
    reviews: 2745,
  },
  {
    id: "sbi3",
    name: "SBI Vistara",
    bank: "SBI Card",
    image: "/cards/sbi-vistara.png",
    categories: ["travel"],
    cashback: 4,
    annualFee: 160,
    joiningBonus: 3000,
    rating: 4.4,
    reviews: 1923,
  },
  {
    id: "sbi4",
    name: "SBI Elite",
    bank: "SBI Card",
    image: "/cards/sbi-elite.png",
    categories: ["travel", "shopping"],
    cashback: 3,
    annualFee: 170,
    joiningBonus: 5000,
    rating: 4.1,
    reviews: 2134,
  },
  {
    id: "sbi5",
    name: "SBI BPCL",
    bank: "SBI Card",
    image: "/cards/sbi-bpcl.png",
    categories: ["fuel"],
    cashback: 7,
    annualFee: 0,
    joiningBonus: 0,
    rating: 3.9,
    reviews: 1456,
  },

  // ICICI Bank Cards
  {
    id: "icici1",
    name: "ICICI Amazon Pay",
    bank: "ICICI Bank",
    image: "/cards/icici-amazon.png",
    categories: ["shopping"],
    cashback: 5,
    annualFee: 130,
    joiningBonus: 1000,
    rating: 4.4,
    reviews: 5234,
  },
  {
    id: "icici2",
    name: "ICICI Sapphiro",
    bank: "ICICI Bank",
    image: "/cards/icici-sapphiro.png",
    categories: ["travel", "shopping", "food"],
    cashback: 3.3,
    annualFee: 190,
    joiningBonus: 3500,
    rating: 4.6,
    reviews: 3456,
  },
  {
    id: "icici3",
    name: "ICICI HPCL",
    bank: "ICICI Bank",
    image: "/cards/icici-hpcl.png",
    categories: ["fuel"],
    cashback: 5,
    annualFee: 105,
    joiningBonus: 500,
    rating: 4.0,
    reviews: 1678,
  },
  {
    id: "icici4",
    name: "ICICI Coral",
    bank: "ICICI Bank",
    image: "/cards/icici-coral.png",
    categories: ["shopping", "food"],
    cashback: 2,
    annualFee: 125,
    joiningBonus: 2000,
    rating: 4.2,
    reviews: 2890,
  },
  {
    id: "icici5",
    name: "ICICI Emeralde",
    bank: "ICICI Bank",
    image: "/cards/icici-emeralde.png",
    categories: ["travel", "shopping"],
    cashback: 4,
    annualFee: 195,
    joiningBonus: 12000,
    rating: 4.8,
    reviews: 4123,
  },

  // Axis Bank Cards
  {
    id: "axis1",
    name: "Axis Flipkart",
    bank: "Axis Bank",
    image: "/cards/axis-flipkart.png",
    categories: ["shopping"],
    cashback: 4,
    annualFee: 135,
    joiningBonus: 500,
    rating: 4.3,
    reviews: 4567,
  },
  {
    id: "axis2",
    name: "Axis Magnus",
    bank: "Axis Bank",
    image: "/cards/axis-magnus.png",
    categories: ["travel", "shopping", "food"],
    cashback: 4.8,
    annualFee: 200,
    joiningBonus: 25000,
    rating: 4.9,
    reviews: 6234,
  },
  {
    id: "axis3",
    name: "Axis Vistara",
    bank: "Axis Bank",
    image: "/cards/axis-vistara.png",
    categories: ["travel"],
    cashback: 4,
    annualFee: 145,
    joiningBonus: 1500,
    rating: 4.5,
    reviews: 2345,
  },
  {
    id: "axis4",
    name: "Axis ACE",
    bank: "Axis Bank",
    image: "/cards/axis-ace.png",
    categories: ["shopping", "food", "fuel"],
    cashback: 2,
    annualFee: 0,
    joiningBonus: 0,
    rating: 4.1,
    reviews: 3789,
  },
  {
    id: "axis5",
    name: "Axis Select",
    bank: "Axis Bank",
    image: "/cards/axis-select.png",
    categories: ["shopping", "travel"],
    cashback: 2,
    annualFee: 155,
    joiningBonus: 3000,
    rating: 4.0,
    reviews: 2567,
  },
];
